// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCduFKlFyyw1cwpZ9IhIPb4hkpGSE5UbgM',
    appId: '1:811985705461:android:e2e105b8b6c678cf5868bc',
    messagingSenderId: '811985705461',
    projectId: 'connect-6204b',
    storageBucket: 'connect-6204b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZmYfFvdtZMfzZDXnj8Lt-5FFjlTkBiSg',
    appId: '1:811985705461:ios:31fd721729c64a2d5868bc',
    messagingSenderId: '811985705461',
    projectId: 'connect-6204b',
    storageBucket: 'connect-6204b.appspot.com',
    androidClientId: '811985705461-r6ipgla6io6v34eudan8aekf82gnrugv.apps.googleusercontent.com',
    iosClientId: '811985705461-j2mktacoekfe5gd1gs15mt8unqkqcluq.apps.googleusercontent.com',
    iosBundleId: 'com.sasanktumpati.connect',
  );
}
